spring:
  application:
    name: spring-mvc-practice202605

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB # ? ???
      max-request-size: 20MB # ? ???



blog:
  file-directory: /Users/stephen/Desktop/codeit-13th-develop/spring-upload